name: Update Major Version Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  update-majorver:
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@v1
